apiVersion: v2
name: vrc-queue-monitor
description: VRChat グループインスタンスの待機列モニタリングシステム
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - vrchat
  - monitor
  - queue

maintainers:
  - name: p-nasimonan
    url: https://github.com/p-nasimonan
